services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    container_name: keycloak-authorization-server

    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: debug

    volumes:
      - ./providers/keycloak:/opt/keycloak/providers

    command: ["start-dev",
              "--http-port", "7080",
              "--https-port", "7443"]

    ports:
      - "7080:7080"
      - "7443:7443"

  mysql-db:
    image: mysql:8.0.40
    container_name: mysql-database

    environment:
      MYSQL_DATABASE: "medical-record"
      MYSQL_USER: "medical_record"
      MYSQL_PASSWORD: "medical_record"
      MYSQL_ROOT_PASSWORD: "secure_password"

    ports: ["3306:3306"]
    expose: ["3306"]
    volumes: ["mysqldata:/data/db"]

volumes:
  mysqldata:
    driver: local